### PR TITLE
State of Health Documentation

### LINKED ISSUE #3: The Scenario section still references experiment and host apps
https://phenix.sceptre.dev/configuration/#scenario

There are still references to the experiment and host apps, but that no longer exists and there are just "apps" now.

### PR DESCRIPTION
**Pull request by activeshadow**
/cc @glattercj @c-abate

We've added some initial documentation for State of Health, and it would be great if one or both of you could take a look at it in th near future. It's not complete, and we'll be adding more next week, but if you get a chance please do take a look.

The best way to view it would be to do the following:

```
$> git clone -b soh https://github.com/activeshadow/phenix-docs.git
$> cd phenix-docs && make serve-docs
$> firefox http://localhost:8000
```
This assumes you have both Docker and Make installed locally already.

closes #3

### CODE REVIEW

**Comment by glattercj** [comment]
- Make all the images larger
- For reachability, is there a configurable wait time for the experiment to boot? When is this test performed?
- Can you use interface names vs IP address i.e. hostListeners?

@c-abate

**Comment by activeshadow** [comment]
>     * For reachability, is there a configurable wait time for the experiment to boot? When is this test performed?

Reachability tests don't start until C2 is active for all VMs. The amount of time to wait for C2 to become active is configurable, and defaults to 5 minutes. Network reachability testing is run in the post-start stage and each time the running stage is triggered.

>     * Can you use interface names vs IP address i.e. hostListeners?

As of now, no you cannot. When you say "interface names" I assume you mean the name given to the interface in the topology configuration, and not the name of the interface used in the OS, correct?

**Comment by glattercj** [comment]
> Reachability tests are run in the post-start stage and each time the running stage is triggered.

I'm assuming the running stage can be triggered via the `manual refresh` button? If yes, you might point that out in the docs.

**Comment by glattercj** [comment]
> As of now, no you cannot. When you say "interface names" I assume you mean the name given to the interface in the topology configuration, and not the name of the interface used in the OS, correct?

I initially meant the OS, but now it makes more sense to use the topology interface names as a reference. Then it would be an easy lookup to get the IP. Since the OS names would be harder to get.

**Comment by activeshadow** [comment]
> I'm assuming the running stage can be triggered via the `manual refresh` button? If yes, you might point that out in the docs.

Well, that was one of the original intents, but I'm glad you brought this up because as of now it's not wired up. The running stage can be triggered manually from the command line using `phenix experiment trigger-running <exp name> <app name>`.

We'll update the docs to reflect this stuff accordingly.

**Comment by activeshadow** [comment]
> I initially meant the OS, but now it makes more sense to use the topology interface names as a reference. Then it would be an easy lookup to get the IP. Since the OS names would be harder to get.

Yeah, if/when we were to do this, I would suggest using the interface name in the topology. If you want, create a feature issue in the phenix repo and we'll get to it when we can.

**Comment by c-abate** [comment]
* rearrange the text and first 2 images.  Text first then images
```
Button available on Experiments table:
<image>

Button available in running experiment:
<image>
```

* Agree with Casey, larger images
* In network reachability C2 is mentioned, but not defined.  I'm assuming this is the control channel through Miniccc?
* If a VM starts up without its interfaces set (which I've seen happen) and the c2Timeout occurs, is there a way to manually kick off the network test later on after the interfaces get setup manually?
* A little excerpt at the beginning to discuss how the SoH works with miniccc would be helpful as well

**Comment by activeshadow** [comment]
@c-abate I think the latest commits have addressed your comments.

**Comment by c-abate** [comment]
Yep it looks good! Thanks.

**Pull request merged**
